version: "3.7"
services:
  backend:
    image: 375296822047.dkr.ecr.ap-northeast-2.amazonaws.com/teamsole/teamsole:latest
    container_name: backend
    network_mode: "host"

  nginx:
    depends_on:
      - backend
    network_mode: "host"
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./.platform/nginx